import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";
import {
  BookIcon,
  Sparkles,
  ShoppingBag,
  MonitorCog,
  Terminal,
  Map,
  Code,
  Share2,
  Package,
  Image,
  Activity,
  Brain,
  Briefcase,
  ChartBar,
  Clipboard,
  Clock,
  CreditCard,
  DollarSign,
  FileText,
  Globe,
  LayoutPanelTop,
  Cloud,
  Zap,
  TrendingUp,
  Paintbrush,
  Settings,
  HelpCircle,
  GitCompare,
  Building2,
  RocketIcon,
} from "lucide-react";
import * as Tabs from "fumadocs-ui/components/tabs";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    BookIcon,
    Sparkles,
    MonitorCog,
    Terminal,
    Map,
    Code,
    Package,
    Image,
    Activity,
    Brain,
    Briefcase,
    ChartBar,
    Clipboard,
    Clock,
    CreditCard,
    DollarSign,
    FileText,
    Globe,
    Share2,
    LayoutPanelTop,
    ShoppingBag,
    Cloud,
    Zap,
    TrendingUp,
    Paintbrush,
    Settings,
    HelpCircle,
    GitCompare,
    Building2,
    RocketIcon,
    Tabs: Tabs.Tabs,
    ...components,
  };
}
